### ISSUE TITLE
Moving Jobs

### ISSUE THREAD

**Issue by BearLoaf** [IsaacMulcahy/RPG-AI-SYSTEM-WIKI#8]
**Is your feature request related to a problem? Please describe.**
Having a Job location, and Resource location be a movable objective. Such as a Hunter, and prey. 

**Describe the solution you'd like**
A job (Hunter) And a Location that can be multiple pre-selected areas or a roaming path. They would find job targets (Prey) kill, and return meat, and pelts. 

**Describe alternatives you've considered**
An attempted job with the current system but noticed issues with a location being moved while jobs are in action. Possible issue with my own workflow, however, a more streamlined hunter job would be a good prefab for the system.

**Additional context**
This may be an extension of the multi-job system you already have working or the randomized job workflow.

**Comment by IsaacMulcahy** [comment]
Hi BearLoaf, 

thanks for getting in touch. You've provided a good amount of detail but I've got a few questions which it would be great for you to answer to drill down a bit more if you don't mind.

1. If you have tried to do this behavior yourself could you provide either the export (Resources/inactive/Name of Export) or a photo of it in a pinch?
2. Location with movement could be due to the way the system works with providing updates to way points as these are only figured out on a new action being assigned. Would having a selectable state on the actions to allow for updates of the way point each loop help with this? 
3. Pre-selected areas could already be supported using work spaces zones, here is the [wiki](https://github.com/IsaacMulcahy/RPG-AI-SYSTEM-WIKI/wiki/Civil-System#zones), let me know what you think of this? It is planned to be expanded upon (e.g. setting the size for each, allow for infinite amount of them etc) 
4. Having pathways predefined have also been created but currently actions can't be done between each node of the path, this is something I'm looking into adding in the near future, how they currently work can be seen here in the [wiki](https://github.com/IsaacMulcahy/RPG-AI-SYSTEM-WIKI/wiki/Civil-System#route). Is this useful?

Regarding additional context you are correct about the work for randomized job workflow being under production, it should also support quite a lot more options as it's being developed to allow for this logic to be switched out at ease between each node and is being used to develop a 'needs' system (think hunger, sleep etc). Hoping to have a version of this out by new years. 

Let me know if I've missed anything or need more info to be able to answer my questions

**Comment by IsaacMulcahy** [comment]
Hi again BearLoaf, 

Let me know what you think of the above and I'll start progressing this.

Thanks,

Isaac

**Comment by BearLoaf** [comment]
1: I was unable to replicate my errors. During testing, I may have broken a
vital function and was forced to do an install of the testing project.
Unfortunately, I could rebuild if entirely necessary.

I'll try with the current system again and see if there is something I can
put together but you already have a  good plan ahead of you and my time
might be better spent elsewhere. The current expansion you have planned my
put to rest all of the little hiccups I'm having. Though I was able to just
make a hunting region and do it their way, granted they don't chase down
prey (Without use from other AI I'm using) And that works just fine.

In any case, I'm really enjoying the flexibility of the project already and
look forwards to pushing it to it's limits as it expands.

**Comment by IsaacMulcahy** [comment]
Great the hear you have a solution and like the next steps I have mentioned. I'm planning to do an variations in workflow release fairly soon which I'll bundle in the 'selectable state on the actions to allow for updates each loop option'. We can then tweak this and see how it goes. 

[If you do have time a review would be great ](https://assetstore.unity.com/packages/tools/ai/civil-ai-system-231069#reviews )

I'll also keep the ticket open and inform you of when the fix is out, if I can help any further please let me know and I'll do my best to help!

**Comment by IsaacMulcahy** [comment]
Hi BearLoaf, 

Hope things are going well and you are still enjoying the product. I just wanted to reach out and let you know the 'Update Each Loop' work has been completed and is coming out with the Minor 0.2.0 Release which is just awaiting on Unity to approve. I will leave another comment when it is out. 

Let me know if you have any other questions or need anything else.

Thanks,

Isaac

**Comment by BearLoaf** [comment]
Fantastic news! The product has been working well.

**Comment by IsaacMulcahy** [comment]
That's great to hear, really means a lot. If you do find the time to leave a review on the asset store it would really [help me out](https://assetstore.unity.com/packages/tools/ai/civil-ai-system-231069#reviews) as I'm just one out on getting an average

**Comment by IsaacMulcahy** [comment]
Hi BearLoaf, apologies for the spam but the new version (0.2.0) has been approved and is available. Let me know if you need anything else, if not I'll be closing off the ticket.

Thanks for your patience with this and hope you continue enjoying the product! 

[If you do have time to leave a review it would be greatly appreciated](https://assetstore.unity.com/packages/tools/ai/civil-ai-system-231069#reviews)
